### ISSUE TITLE
Few issues to fix for the kubearmor-website

### ISSUE THREAD

**Issue by nyrahul** [accuknox/KubeArmor-website#16]
- The blog still points to my private github repo file. It should ideally be hosted on the website/portal itself.
- The yaml line spacing should be reduced and it should look like code. There are examples on [this page](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/).
- The roadmap has scope for much improvement.

**Comment by ankita10119** [comment]
Got it @nyrahul , will target next week

**Comment by nyrahul** [comment]
Add a video: https://drive.google.com/file/d/1hgf9wRS8KBQVcojgx48NOCLckdzCRFT_/view?usp=sharing
